name: app_tieng_anh_de_an
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  shared_preferences: ^2.5.2

  http: ^0.13.6

  # State management
  flutter_bloc: ^9.1.0
  flutter_tts: ^3.8.3
  equatable: ^2.0.7
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  firebase_core: ^3.12.1
  image: ^4.1.7
  flutter_image_compress: ^2.4.0
  google_sign_in: ^6.1.4  # hoặc version mới nhất
  intl: ^0.20.2
  fl_chart: ^0.70.2
  flutter_card_swiper: ^7.0.2


dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic