// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx8UACLfJYTtZLuiamQe_W6VTCq1cAzIc',
    appId: '1:347523440233:web:d09c7ce552061822c34cf8',
    messagingSenderId: '347523440233',
    projectId: 'flutter2004-2025',
    authDomain: 'flutter2004-2025.firebaseapp.com',
    storageBucket: 'flutter2004-2025.firebasestorage.app',
    measurementId: 'G-RT4NWMEHEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv0O7fH3HkNtYiTKnZ0DvFWxxhyddFY5I',
    appId: '1:347523440233:android:e641a47466386235c34cf8',
    messagingSenderId: '347523440233',
    projectId: 'flutter2004-2025',
    storageBucket: 'flutter2004-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcECkc8Pgxs1BAlG8ptbmQoFnoQ2yVOiM',
    appId: '1:347523440233:ios:5db6521caaf0ae75c34cf8',
    messagingSenderId: '347523440233',
    projectId: 'flutter2004-2025',
    storageBucket: 'flutter2004-2025.firebasestorage.app',
    iosBundleId: 'com.example.appTiengAnhDeAn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcECkc8Pgxs1BAlG8ptbmQoFnoQ2yVOiM',
    appId: '1:347523440233:ios:5db6521caaf0ae75c34cf8',
    messagingSenderId: '347523440233',
    projectId: 'flutter2004-2025',
    storageBucket: 'flutter2004-2025.firebasestorage.app',
    iosBundleId: 'com.example.appTiengAnhDeAn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx8UACLfJYTtZLuiamQe_W6VTCq1cAzIc',
    appId: '1:347523440233:web:acbdaa5425d01b9ec34cf8',
    messagingSenderId: '347523440233',
    projectId: 'flutter2004-2025',
    authDomain: 'flutter2004-2025.firebaseapp.com',
    storageBucket: 'flutter2004-2025.firebasestorage.app',
    measurementId: 'G-0YXCHNBMHP',
  );
}
